# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04963a7b4fa7c2b99c8c7c2a7fd908adaf1478f9d7339123b0df62a9fb115c216d3faf85826f1ad2b891082deab75dfa663c390f024f1e4dcaa9b367205acbe4

test:
  secret_key_base: 2fb6a0ef8d72facb1dbcf10ebe0734ca8a3b0fb290ca5a9d66b48acbe2ffc84e501e42b96a2d6399204f0979f29cfeb40989f2ea91cb9cf803075aee0d718b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
